name: Terraform Deployment

on:
  workflow_dispatch: # Allows manual triggering of the workflow from the Actions tab

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

     
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./terraform

      
      - name: Terraform Apply
        if: github.event.inputs.approve == 'true'
        run: terraform apply tfplan
        working-directory: ./terraform

