
name: CI

on: [push]

jobs:
  sast_scan:
    name: Run Bandit Scan
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: Set Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: install Bandit
      run: pip install bandit
      
    - name: Run bandit Scan
      run: bandit -r . -f json -o bandit_report.json

      
  

